/**
 * Monthly sales report — build an HTML page from a month's orders, render it to
 * a PDF on the device (expo-print), archive it to Supabase, and open the share
 * sheet so the owner can save or send it.
 */
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { fetchOrdersInRange } from '../data/fetch';
import { uploadReport } from '../data/upload';
import { isSupabaseConfigured } from '../data/supabase';
import type { Order } from '../data/types';

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

const rupee = (n: number) => `₹${n.toLocaleString('en-IN')}`;
const esc = (s: string) =>
  s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));

function buildHtml(orders: Order[], kitchenName: string, monthLabel: string): string {
  // Only paid/completed orders count as real sales.
  const sales = orders.filter((o) => o.status === 'Completed' || o.total > 0);
  const revenue = sales.reduce((sum, o) => sum + o.total, 0);

  // Totals per dish across the month.
  const dishTotals = new Map<string, { name: string; qty: number; value: number }>();
  for (const o of sales) {
    for (const l of o.lines) {
      const e = dishTotals.get(l.name) ?? { name: l.name, qty: 0, value: 0 };
      e.qty += l.quantity;
      e.value += l.quantity * l.price;
      dishTotals.set(l.name, e);
    }
  }
  const topDishes = [...dishTotals.values()].sort((a, b) => b.qty - a.qty);

  const orderRows = sales
    .map((o) => {
      const items = o.lines
        .map((l, i) => `${i + 1}. ${esc(l.name)} ×${l.quantity}`)
        .join('<br/>');
      return `<tr>
        <td>${esc(o.ref)}</td>
        <td>${esc(o.slotCode)}</td>
        <td>${esc(o.customerName)}</td>
        <td>${items}</td>
        <td class="num">${rupee(o.total)}</td>
      </tr>`;
    })
    .join('');

  const dishRows = topDishes
    .map((d) => `<tr><td>${esc(d.name)}</td><td class="num">${d.qty}</td><td class="num">${rupee(d.value)}</td></tr>`)
    .join('');

  return `<!doctype html><html><head><meta charset="utf-8"/>
  <style>
    * { font-family: -apple-system, Roboto, sans-serif; }
    body { color: #2B1D12; padding: 28px; }
    h1 { color: #C1440E; margin: 0; font-size: 24px; }
    .sub { color: #6b5847; margin: 2px 0 20px; }
    .cards { display: flex; gap: 12px; margin-bottom: 22px; }
    .card { flex: 1; border: 1px solid #EADBC6; border-radius: 10px; padding: 12px 14px; }
    .card .k { color: #6b5847; font-size: 12px; }
    .card .v { color: #C1440E; font-size: 22px; font-weight: 800; }
    h2 { font-size: 15px; margin: 22px 0 8px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th, td { text-align: left; padding: 7px 8px; border-bottom: 1px solid #EADBC6; vertical-align: top; }
    th { color: #6b5847; text-transform: uppercase; font-size: 10px; letter-spacing: .04em; }
    .num { text-align: right; white-space: nowrap; }
    .foot { margin-top: 22px; color: #9b8977; font-size: 11px; }
  </style></head><body>
    <h1>${esc(kitchenName)}</h1>
    <div class="sub">Sales report · ${esc(monthLabel)}</div>
    <div class="cards">
      <div class="card"><div class="k">Orders</div><div class="v">${sales.length}</div></div>
      <div class="card"><div class="k">Revenue</div><div class="v">${rupee(revenue)}</div></div>
      <div class="card"><div class="k">Items sold</div><div class="v">${topDishes.reduce((s, d) => s + d.qty, 0)}</div></div>
    </div>

    <h2>By dish</h2>
    <table><thead><tr><th>Dish</th><th class="num">Qty</th><th class="num">Value</th></tr></thead>
      <tbody>${dishRows || '<tr><td colspan="3">No sales this month.</td></tr>'}</tbody></table>

    <h2>Orders</h2>
    <table><thead><tr><th>Ref</th><th>Code</th><th>Customer</th><th>Items</th><th class="num">Total</th></tr></thead>
      <tbody>${orderRows || '<tr><td colspan="5">No orders this month.</td></tr>'}</tbody></table>

    <div class="foot">Generated by Nandhan Delight · Hot · Homemade · Tiruppur</div>
  </body></html>`;
}

export type ReportResult = { ok: boolean; count: number; revenue: number; error?: string };

/** Build, archive, and share the PDF for one month. `month` is 0-11. */
export async function generateMonthlyReport(
  kitchenSlug: string,
  kitchenName: string,
  year: number,
  month: number,
): Promise<ReportResult> {
  try {
    const start = new Date(year, month, 1).toISOString();
    const end = new Date(year, month + 1, 1).toISOString();
    const orders = await fetchOrdersInRange(kitchenSlug, start, end);
    const monthLabel = `${MONTHS[month]} ${year}`;

    const html = buildHtml(orders, kitchenName, monthLabel);
    const { uri } = await Print.printToFileAsync({ html });

    // Archive to Supabase (best-effort) so it's downloadable later.
    if (isSupabaseConfigured) {
      const mm = String(month + 1).padStart(2, '0');
      void uploadReport(kitchenSlug, `${year}-${mm}.pdf`, uri);
    }

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Sales report · ${monthLabel}` });
    }

    const revenue = orders.reduce((s, o) => s + o.total, 0);
    return { ok: true, count: orders.length, revenue };
  } catch (e) {
    console.warn('[spice-route] generateMonthlyReport failed', e);
    return { ok: false, count: 0, revenue: 0, error: String(e) };
  }
}

export { MONTHS };
